### ISSUE TITLE
Output any marks for a packet?

### ISSUE THREAD

**Issue by lollipopman** [x-way/iptables-tracer#44]
Would it be possible for this tool to output any iptables marks associated with the packet?

**Comment by x-way** [comment]
By default iptables-tracer prints out the mark of a packet (also called skbuf mark or fwmark).
If the kernel supports retrieving the conntrack information of a packet via NFLOG, the `-x` option can be used to also print out the conntrack mark and the other conntrack information:
```
# iptables-tracer -f "-p udp --dport 53" -x
22:57:21.592960 filter INPUT   0x00000123 NEW O 0x00000876 IP 192.168.231.179.63712 > 10.43.117.6.53: 10107+ [1au] A? ip.sigint.ch. (41)  [In:eth0 Out:]
 CT: orig=udp:192.168.231.179:63712->10.43.117.6:53, reply=udp:10.43.117.6:53->192.168.231.179:63712, timeout=0s, id=0x0402a180, status=
```
In this example the value of the mark/fwmark is ` 0x00000123`and the value of the conntrack mark is `0x00000876`.

Does this provide the mark information you need, or did you have another output in mind?

**Comment by lollipopman** [comment]
@x-way thanks that is perfect, I didn't realize what those hex values were in the output. Thanks for creating such a great iptables debugging tool.
